spring:
  datasource:
    driver-clss-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  jpa:
    show-sql: true

server:
  port: 8888

